package com.training.sdet.day1;

class A{
	A(int x) {
		System.out.println("Hey I'm from Class A");
	}
}

//Parameter Constructor
class B extends A{
	B(int x){
		super(x); //Generated by compiler
		System.out.println("Hey I'm from Class B");
	}
}

public class InheritenceExample {
	public static void main(String[] args) {
		B objB = new B(10);
		
		
	}

}
